name: crypto
version: 2.2.0-nullsafety-dev
description: Implementations of SHA, MD5, and HMAC cryptographic functions
homepage: https://www.github.com/dart-lang/crypto

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety
  convert: ^3.0.0-nullsafety
  typed_data: ^1.3.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety

dependency_overrides:
  convert:
    git: git://github.com/dart-lang/convert.git
